{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Cloning into 'temporal-fusion-transformer'...\n",
      "remote: Enumerating objects: 1898, done.\u001b[K\n",
      "remote: Total 1898 (delta 0), reused 0 (delta 0), pack-reused 1898\u001b[K\n",
      "Receiving objects: 100% (1898/1898), 458.75 MiB | 53.09 MiB/s, done.\n",
      "Resolving deltas: 100% (381/381), done.\n",
      "Checking out files: 100% (954/954), done.\n"
     ]
    }
   ],
   "source": [
    "!git clone https://github.com/fornasari12/time-series-forecasting.git"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "4\n"
     ]
    }
   ],
   "source": [
    "!nvidia-smi --query-gpu=name --format=csv,noheader | wc -l"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/opt/conda/lib/python3.7/site-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead\n",
      "  from cryptography.utils import int_from_bytes\n",
      "/opt/conda/lib/python3.7/site-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead\n",
      "  from cryptography.utils import int_from_bytes\n",
      "Looking in links: https://download.pytorch.org/whl/torch_stable.html\n",
      "Collecting torch==1.7.1+cu110\n",
      "  Downloading https://download.pytorch.org/whl/cu110/torch-1.7.1%2Bcu110-cp37-cp37m-linux_x86_64.whl (1156.8 MB)\n",
      "     |████████████████████████████████| 1156.8 MB 7.3 kB/s              \n",
      "\u001b[?25hCollecting torchvision==0.8.2+cu110\n",
      "  Downloading https://download.pytorch.org/whl/cu110/torchvision-0.8.2%2Bcu110-cp37-cp37m-linux_x86_64.whl (12.9 MB)\n",
      "     |████████████████████████████████| 12.9 MB 95.1 MB/s            \n",
      "\u001b[?25hCollecting torchaudio==0.7.2\n",
      "  Downloading torchaudio-0.7.2-cp37-cp37m-manylinux1_x86_64.whl (7.6 MB)\n",
      "     |████████████████████████████████| 7.6 MB 22.0 MB/s            \n",
      "\u001b[?25hRequirement already satisfied: typing-extensions in /opt/conda/lib/python3.7/site-packages (from torch==1.7.1+cu110) (3.10.0.2)\n",
      "Requirement already satisfied: numpy in /opt/conda/lib/python3.7/site-packages (from torch==1.7.1+cu110) (1.20.3)\n",
      "Requirement already satisfied: pillow>=4.1.1 in /opt/conda/lib/python3.7/site-packages (from torchvision==0.8.2+cu110) (8.4.0)\n",
      "Installing collected packages: torch, torchvision, torchaudio\n",
      "Successfully installed torch-1.7.1+cu110 torchaudio-0.7.2 torchvision-0.8.2+cu110\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "!pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "True"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import torch\n",
    "\n",
    "torch.cuda.is_available()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/opt/conda/lib/python3.7/site-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead\n",
      "  from cryptography.utils import int_from_bytes\n",
      "/opt/conda/lib/python3.7/site-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead\n",
      "  from cryptography.utils import int_from_bytes\n",
      "Collecting pytorch-forecasting\n",
      "  Downloading pytorch_forecasting-0.9.2-py3-none-any.whl (113 kB)\n",
      "     |████████████████████████████████| 113 kB 27.1 MB/s            \n",
      "\u001b[?25hRequirement already satisfied: matplotlib in /opt/conda/lib/python3.7/site-packages (from pytorch-forecasting) (3.1.3)\n",
      "Collecting scikit-learn<1.1,>=0.24\n",
      "  Downloading scikit_learn-1.0.1-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (23.2 MB)\n",
      "     |████████████████████████████████| 23.2 MB 102.6 MB/s            \n",
      "\u001b[?25hRequirement already satisfied: scipy in /opt/conda/lib/python3.7/site-packages (from pytorch-forecasting) (1.4.1)\n",
      "Collecting optuna<3.0.0,>=2.3.0\n",
      "  Downloading optuna-2.10.0-py3-none-any.whl (308 kB)\n",
      "     |████████████████████████████████| 308 kB 109.5 MB/s            \n",
      "\u001b[?25hCollecting pytorch-lightning<2.0.0,>=1.2.4\n",
      "  Downloading pytorch_lightning-1.5.4-py3-none-any.whl (524 kB)\n",
      "     |████████████████████████████████| 524 kB 119.7 MB/s            \n",
      "\u001b[?25hCollecting pandas<2.0.0,>=1.3.0\n",
      "  Downloading pandas-1.3.4-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.3 MB)\n",
      "     |████████████████████████████████| 11.3 MB 66.7 MB/s            \n",
      "\u001b[?25hRequirement already satisfied: torch<2.0,>=1.7 in /opt/conda/lib/python3.7/site-packages (from pytorch-forecasting) (1.7.1+cu110)\n",
      "Requirement already satisfied: statsmodels in /opt/conda/lib/python3.7/site-packages (from pytorch-forecasting) (0.11.0)\n",
      "Requirement already satisfied: tqdm in /opt/conda/lib/python3.7/site-packages (from optuna<3.0.0,>=2.3.0->pytorch-forecasting) (4.42.1)\n",
      "Requirement already satisfied: PyYAML in /opt/conda/lib/python3.7/site-packages (from optuna<3.0.0,>=2.3.0->pytorch-forecasting) (6.0)\n",
      "Requirement already satisfied: numpy in /opt/conda/lib/python3.7/site-packages (from optuna<3.0.0,>=2.3.0->pytorch-forecasting) (1.20.3)\n",
      "Collecting alembic\n",
      "  Downloading alembic-1.7.5-py3-none-any.whl (209 kB)\n",
      "     |████████████████████████████████| 209 kB 97.2 MB/s            \n",
      "\u001b[?25hRequirement already satisfied: sqlalchemy>=1.1.0 in /opt/conda/lib/python3.7/site-packages (from optuna<3.0.0,>=2.3.0->pytorch-forecasting) (1.3.13)\n",
      "Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.7/site-packages (from optuna<3.0.0,>=2.3.0->pytorch-forecasting) (20.1)\n",
      "Collecting cmaes>=0.8.2\n",
      "  Downloading cmaes-0.8.2-py3-none-any.whl (15 kB)\n",
      "Collecting cliff\n",
      "  Downloading cliff-3.10.0-py3-none-any.whl (80 kB)\n",
      "     |████████████████████████████████| 80 kB 1.1 MB/s              \n",
      "\u001b[?25hCollecting colorlog\n",
      "  Downloading colorlog-6.6.0-py2.py3-none-any.whl (11 kB)\n",
      "Requirement already satisfied: python-dateutil>=2.7.3 in /opt/conda/lib/python3.7/site-packages (from pandas<2.0.0,>=1.3.0->pytorch-forecasting) (2.8.1)\n",
      "Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.7/site-packages (from pandas<2.0.0,>=1.3.0->pytorch-forecasting) (2019.3)\n",
      "Collecting torchmetrics>=0.4.1\n",
      "  Downloading torchmetrics-0.6.0-py3-none-any.whl (329 kB)\n",
      "     |████████████████████████████████| 329 kB 94.6 MB/s            \n",
      "\u001b[?25hRequirement already satisfied: future>=0.17.1 in /opt/conda/lib/python3.7/site-packages (from pytorch-lightning<2.0.0,>=1.2.4->pytorch-forecasting) (0.18.2)\n",
      "Requirement already satisfied: fsspec[http]!=2021.06.0,>=2021.05.0 in /opt/conda/lib/python3.7/site-packages (from pytorch-lightning<2.0.0,>=1.2.4->pytorch-forecasting) (2021.11.0)\n",
      "Collecting pyDeprecate==0.3.1\n",
      "  Downloading pyDeprecate-0.3.1-py3-none-any.whl (10 kB)\n",
      "Collecting tensorboard>=2.2.0\n",
      "  Downloading tensorboard-2.7.0-py3-none-any.whl (5.8 MB)\n",
      "     |████████████████████████████████| 5.8 MB 65.9 MB/s            \n",
      "\u001b[?25hRequirement already satisfied: typing-extensions in /opt/conda/lib/python3.7/site-packages (from pytorch-lightning<2.0.0,>=1.2.4->pytorch-forecasting) (3.10.0.2)\n",
      "Collecting threadpoolctl>=2.0.0\n",
      "  Downloading threadpoolctl-3.0.0-py3-none-any.whl (14 kB)\n",
      "Requirement already satisfied: joblib>=0.11 in /opt/conda/lib/python3.7/site-packages (from scikit-learn<1.1,>=0.24->pytorch-forecasting) (0.14.1)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.7/site-packages (from matplotlib->pytorch-forecasting) (1.1.0)\n",
      "Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /opt/conda/lib/python3.7/site-packages (from matplotlib->pytorch-forecasting) (2.4.6)\n",
      "Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.7/site-packages (from matplotlib->pytorch-forecasting) (0.10.0)\n",
      "Requirement already satisfied: patsy>=0.5 in /opt/conda/lib/python3.7/site-packages (from statsmodels->pytorch-forecasting) (0.5.1)\n",
      "Requirement already satisfied: six in /opt/conda/lib/python3.7/site-packages (from cycler>=0.10->matplotlib->pytorch-forecasting) (1.14.0)\n",
      "Requirement already satisfied: aiohttp in /opt/conda/lib/python3.7/site-packages (from fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning<2.0.0,>=1.2.4->pytorch-forecasting) (3.8.0)\n",
      "Requirement already satisfied: requests in /opt/conda/lib/python3.7/site-packages (from fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning<2.0.0,>=1.2.4->pytorch-forecasting) (2.26.0)\n",
      "Requirement already satisfied: setuptools in /opt/conda/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib->pytorch-forecasting) (58.5.3)\n",
      "Collecting grpcio>=1.24.3\n",
      "  Downloading grpcio-1.42.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.0 MB)\n",
      "     |████████████████████████████████| 4.0 MB 109.1 MB/s            \n",
      "\u001b[?25hRequirement already satisfied: protobuf>=3.6.0 in /opt/conda/lib/python3.7/site-packages (from tensorboard>=2.2.0->pytorch-lightning<2.0.0,>=1.2.4->pytorch-forecasting) (3.19.1)\n",
      "Collecting markdown>=2.6.8\n",
      "  Downloading Markdown-3.3.6-py3-none-any.whl (97 kB)\n",
      "     |████████████████████████████████| 97 kB 767 kB/s              \n",
      "\u001b[?25hRequirement already satisfied: werkzeug>=0.11.15 in /opt/conda/lib/python3.7/site-packages (from tensorboard>=2.2.0->pytorch-lightning<2.0.0,>=1.2.4->pytorch-forecasting) (1.0.0)\n",
      "Collecting google-auth<3,>=1.6.3\n",
      "  Downloading google_auth-2.3.3-py2.py3-none-any.whl (155 kB)\n",
      "     |████████████████████████████████| 155 kB 108.5 MB/s            \n",
      "\u001b[?25hCollecting tensorboard-data-server<0.7.0,>=0.6.0\n",
      "  Downloading tensorboard_data_server-0.6.1-py3-none-manylinux2010_x86_64.whl (4.9 MB)\n",
      "     |████████████████████████████████| 4.9 MB 53.7 MB/s            \n",
      "\u001b[?25hCollecting tensorboard-plugin-wit>=1.6.0\n",
      "  Downloading tensorboard_plugin_wit-1.8.0-py3-none-any.whl (781 kB)\n",
      "     |████████████████████████████████| 781 kB 63.6 MB/s            \n",
      "\u001b[?25hCollecting absl-py>=0.4\n",
      "  Downloading absl_py-1.0.0-py3-none-any.whl (126 kB)\n",
      "     |████████████████████████████████| 126 kB 115.8 MB/s            \n",
      "\u001b[?25hRequirement already satisfied: wheel>=0.26 in /opt/conda/lib/python3.7/site-packages (from tensorboard>=2.2.0->pytorch-lightning<2.0.0,>=1.2.4->pytorch-forecasting) (0.34.2)\n",
      "Collecting google-auth-oauthlib<0.5,>=0.4.1\n",
      "  Downloading google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)\n",
      "Requirement already satisfied: importlib-metadata in /opt/conda/lib/python3.7/site-packages (from alembic->optuna<3.0.0,>=2.3.0->pytorch-forecasting) (1.5.0)\n",
      "Collecting importlib-resources\n",
      "  Downloading importlib_resources-5.4.0-py3-none-any.whl (28 kB)\n",
      "Collecting Mako\n",
      "  Downloading Mako-1.1.6-py2.py3-none-any.whl (75 kB)\n",
      "     |████████████████████████████████| 75 kB 464 kB/s              \n",
      "\u001b[?25hCollecting stevedore>=2.0.1\n",
      "  Downloading stevedore-3.5.0-py3-none-any.whl (49 kB)\n",
      "     |████████████████████████████████| 49 kB 924 kB/s             \n",
      "\u001b[?25hCollecting PrettyTable>=0.7.2\n",
      "  Downloading prettytable-2.4.0-py3-none-any.whl (24 kB)\n",
      "Collecting pbr!=2.1.0,>=2.0.0\n",
      "  Downloading pbr-5.8.0-py2.py3-none-any.whl (112 kB)\n",
      "     |████████████████████████████████| 112 kB 106.6 MB/s            \n",
      "\u001b[?25hCollecting autopage>=0.4.0\n",
      "  Downloading autopage-0.4.0-py3-none-any.whl (20 kB)\n",
      "Collecting cmd2>=1.0.0\n",
      "  Downloading cmd2-2.3.3-py3-none-any.whl (149 kB)\n",
      "     |████████████████████████████████| 149 kB 134.4 MB/s            \n",
      "\u001b[?25hRequirement already satisfied: attrs>=16.3.0 in /opt/conda/lib/python3.7/site-packages (from cmd2>=1.0.0->cliff->optuna<3.0.0,>=2.3.0->pytorch-forecasting) (19.3.0)\n",
      "Collecting importlib-metadata\n",
      "  Downloading importlib_metadata-4.8.2-py3-none-any.whl (17 kB)\n",
      "Collecting pyperclip>=1.6\n",
      "  Downloading pyperclip-1.8.2.tar.gz (20 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hRequirement already satisfied: wcwidth>=0.1.7 in /opt/conda/lib/python3.7/site-packages (from cmd2>=1.0.0->cliff->optuna<3.0.0,>=2.3.0->pytorch-forecasting) (0.1.8)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /opt/conda/lib/python3.7/site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.2.0->pytorch-lightning<2.0.0,>=1.2.4->pytorch-forecasting) (4.7.2)\n",
      "Collecting pyasn1-modules>=0.2.1\n",
      "  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)\n",
      "     |████████████████████████████████| 155 kB 113.6 MB/s            \n",
      "\u001b[?25hCollecting cachetools<5.0,>=2.0.0\n",
      "  Downloading cachetools-4.2.4-py3-none-any.whl (10 kB)\n",
      "Collecting requests-oauthlib>=0.7.0\n",
      "  Downloading requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)\n",
      "Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.7/site-packages (from importlib-metadata->alembic->optuna<3.0.0,>=2.3.0->pytorch-forecasting) (2.2.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning<2.0.0,>=1.2.4->pytorch-forecasting) (2.8)\n",
      "Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/conda/lib/python3.7/site-packages (from requests->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning<2.0.0,>=1.2.4->pytorch-forecasting) (2.0.4)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.7/site-packages (from requests->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning<2.0.0,>=1.2.4->pytorch-forecasting) (1.26.7)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.7/site-packages (from requests->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning<2.0.0,>=1.2.4->pytorch-forecasting) (2021.10.8)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.7/site-packages (from aiohttp->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning<2.0.0,>=1.2.4->pytorch-forecasting) (1.2.0)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in /opt/conda/lib/python3.7/site-packages (from aiohttp->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning<2.0.0,>=1.2.4->pytorch-forecasting) (1.2.0)\n",
      "Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /opt/conda/lib/python3.7/site-packages (from aiohttp->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning<2.0.0,>=1.2.4->pytorch-forecasting) (4.0.1)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in /opt/conda/lib/python3.7/site-packages (from aiohttp->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning<2.0.0,>=1.2.4->pytorch-forecasting) (1.7.2)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.7/site-packages (from aiohttp->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning<2.0.0,>=1.2.4->pytorch-forecasting) (5.2.0)\n",
      "Requirement already satisfied: asynctest==0.13.0 in /opt/conda/lib/python3.7/site-packages (from aiohttp->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning<2.0.0,>=1.2.4->pytorch-forecasting) (0.13.0)\n",
      "Collecting zipp>=0.5\n",
      "  Downloading zipp-3.6.0-py3-none-any.whl (5.3 kB)\n",
      "Requirement already satisfied: MarkupSafe>=0.9.2 in /opt/conda/lib/python3.7/site-packages (from Mako->alembic->optuna<3.0.0,>=2.3.0->pytorch-forecasting) (2.0.1)\n",
      "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /opt/conda/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard>=2.2.0->pytorch-lightning<2.0.0,>=1.2.4->pytorch-forecasting) (0.4.8)\n",
      "Collecting oauthlib>=3.0.0\n",
      "  Downloading oauthlib-3.1.1-py2.py3-none-any.whl (146 kB)\n",
      "     |████████████████████████████████| 146 kB 120.9 MB/s            \n",
      "\u001b[?25hBuilding wheels for collected packages: pyperclip\n",
      "  Building wheel for pyperclip (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for pyperclip: filename=pyperclip-1.8.2-py3-none-any.whl size=11136 sha256=4f9293f5f54572a45e3409ff6e1cc8050fb3584a785d1d685cc1bfa2ba7e076f\n",
      "  Stored in directory: /root/.cache/pip/wheels/9f/18/84/8f69f8b08169c7bae2dde6bd7daf0c19fca8c8e500ee620a28\n",
      "Successfully built pyperclip\n",
      "Installing collected packages: zipp, pyasn1-modules, oauthlib, cachetools, requests-oauthlib, pyperclip, pbr, importlib-metadata, google-auth, tensorboard-plugin-wit, tensorboard-data-server, stevedore, PrettyTable, markdown, Mako, importlib-resources, grpcio, google-auth-oauthlib, cmd2, autopage, absl-py, torchmetrics, threadpoolctl, tensorboard, pyDeprecate, pandas, colorlog, cmaes, cliff, alembic, scikit-learn, pytorch-lightning, optuna, pytorch-forecasting\n",
      "  Attempting uninstall: zipp\n",
      "    Found existing installation: zipp 2.2.0\n",
      "    Uninstalling zipp-2.2.0:\n",
      "      Successfully uninstalled zipp-2.2.0\n",
      "  Attempting uninstall: importlib-metadata\n",
      "    Found existing installation: importlib-metadata 1.5.0\n",
      "    Uninstalling importlib-metadata-1.5.0:\n",
      "      Successfully uninstalled importlib-metadata-1.5.0\n",
      "  Attempting uninstall: pandas\n",
      "    Found existing installation: pandas 1.0.1\n",
      "    Uninstalling pandas-1.0.1:\n",
      "      Successfully uninstalled pandas-1.0.1\n",
      "  Attempting uninstall: scikit-learn\n",
      "    Found existing installation: scikit-learn 0.22.1\n",
      "    Uninstalling scikit-learn-0.22.1:\n",
      "      Successfully uninstalled scikit-learn-0.22.1\n",
      "\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "pytest-astropy 0.8.0 requires pytest-cov>=2.0, which is not installed.\n",
      "pytest-astropy 0.8.0 requires pytest-filter-subpackage>=0.1, which is not installed.\n",
      "docker-compose 1.29.2 requires PyYAML<6,>=3.10, but you have pyyaml 6.0 which is incompatible.\u001b[0m\n",
      "Successfully installed Mako-1.1.6 PrettyTable-2.4.0 absl-py-1.0.0 alembic-1.7.5 autopage-0.4.0 cachetools-4.2.4 cliff-3.10.0 cmaes-0.8.2 cmd2-2.3.3 colorlog-6.6.0 google-auth-2.3.3 google-auth-oauthlib-0.4.6 grpcio-1.42.0 importlib-metadata-4.8.2 importlib-resources-5.4.0 markdown-3.3.6 oauthlib-3.1.1 optuna-2.10.0 pandas-1.3.4 pbr-5.8.0 pyDeprecate-0.3.1 pyasn1-modules-0.2.8 pyperclip-1.8.2 pytorch-forecasting-0.9.2 pytorch-lightning-1.5.4 requests-oauthlib-1.3.0 scikit-learn-1.0.1 stevedore-3.5.0 tensorboard-2.7.0 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.0 threadpoolctl-3.0.0 torchmetrics-0.6.0 zipp-3.6.0\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\n",
      "/opt/conda/lib/python3.7/site-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead\n",
      "  from cryptography.utils import int_from_bytes\n",
      "/opt/conda/lib/python3.7/site-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead\n",
      "  from cryptography.utils import int_from_bytes\n",
      "Requirement already satisfied: pytorch-lightning in /opt/conda/lib/python3.7/site-packages (1.5.4)\n",
      "Requirement already satisfied: fsspec[http]!=2021.06.0,>=2021.05.0 in /opt/conda/lib/python3.7/site-packages (from pytorch-lightning) (2021.11.0)\n",
      "Requirement already satisfied: torch>=1.7.* in /opt/conda/lib/python3.7/site-packages (from pytorch-lightning) (1.7.1+cu110)\n",
      "Requirement already satisfied: tensorboard>=2.2.0 in /opt/conda/lib/python3.7/site-packages (from pytorch-lightning) (2.7.0)\n",
      "Requirement already satisfied: tqdm>=4.41.0 in /opt/conda/lib/python3.7/site-packages (from pytorch-lightning) (4.42.1)\n",
      "Requirement already satisfied: torchmetrics>=0.4.1 in /opt/conda/lib/python3.7/site-packages (from pytorch-lightning) (0.6.0)\n",
      "Requirement already satisfied: PyYAML>=5.1 in /opt/conda/lib/python3.7/site-packages (from pytorch-lightning) (6.0)\n",
      "Requirement already satisfied: packaging>=17.0 in /opt/conda/lib/python3.7/site-packages (from pytorch-lightning) (20.1)\n",
      "Requirement already satisfied: typing-extensions in /opt/conda/lib/python3.7/site-packages (from pytorch-lightning) (3.10.0.2)\n",
      "Requirement already satisfied: future>=0.17.1 in /opt/conda/lib/python3.7/site-packages (from pytorch-lightning) (0.18.2)\n",
      "Requirement already satisfied: numpy>=1.17.2 in /opt/conda/lib/python3.7/site-packages (from pytorch-lightning) (1.20.3)\n",
      "Requirement already satisfied: pyDeprecate==0.3.1 in /opt/conda/lib/python3.7/site-packages (from pytorch-lightning) (0.3.1)\n",
      "Requirement already satisfied: aiohttp in /opt/conda/lib/python3.7/site-packages (from fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning) (3.8.0)\n",
      "Requirement already satisfied: requests in /opt/conda/lib/python3.7/site-packages (from fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning) (2.26.0)\n",
      "Requirement already satisfied: six in /opt/conda/lib/python3.7/site-packages (from packaging>=17.0->pytorch-lightning) (1.14.0)\n",
      "Requirement already satisfied: pyparsing>=2.0.2 in /opt/conda/lib/python3.7/site-packages (from packaging>=17.0->pytorch-lightning) (2.4.6)\n",
      "Requirement already satisfied: google-auth<3,>=1.6.3 in /opt/conda/lib/python3.7/site-packages (from tensorboard>=2.2.0->pytorch-lightning) (2.3.3)\n",
      "Requirement already satisfied: markdown>=2.6.8 in /opt/conda/lib/python3.7/site-packages (from tensorboard>=2.2.0->pytorch-lightning) (3.3.6)\n",
      "Requirement already satisfied: werkzeug>=0.11.15 in /opt/conda/lib/python3.7/site-packages (from tensorboard>=2.2.0->pytorch-lightning) (1.0.0)\n",
      "Requirement already satisfied: wheel>=0.26 in /opt/conda/lib/python3.7/site-packages (from tensorboard>=2.2.0->pytorch-lightning) (0.34.2)\n",
      "Requirement already satisfied: grpcio>=1.24.3 in /opt/conda/lib/python3.7/site-packages (from tensorboard>=2.2.0->pytorch-lightning) (1.42.0)\n",
      "Requirement already satisfied: setuptools>=41.0.0 in /opt/conda/lib/python3.7/site-packages (from tensorboard>=2.2.0->pytorch-lightning) (58.5.3)\n",
      "Requirement already satisfied: absl-py>=0.4 in /opt/conda/lib/python3.7/site-packages (from tensorboard>=2.2.0->pytorch-lightning) (1.0.0)\n",
      "Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /opt/conda/lib/python3.7/site-packages (from tensorboard>=2.2.0->pytorch-lightning) (0.4.6)\n",
      "Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /opt/conda/lib/python3.7/site-packages (from tensorboard>=2.2.0->pytorch-lightning) (0.6.1)\n",
      "Requirement already satisfied: protobuf>=3.6.0 in /opt/conda/lib/python3.7/site-packages (from tensorboard>=2.2.0->pytorch-lightning) (3.19.1)\n",
      "Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /opt/conda/lib/python3.7/site-packages (from tensorboard>=2.2.0->pytorch-lightning) (1.8.0)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.7/site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.2.0->pytorch-lightning) (0.2.8)\n",
      "Requirement already satisfied: cachetools<5.0,>=2.0.0 in /opt/conda/lib/python3.7/site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.2.0->pytorch-lightning) (4.2.4)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /opt/conda/lib/python3.7/site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.2.0->pytorch-lightning) (4.7.2)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in /opt/conda/lib/python3.7/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.2.0->pytorch-lightning) (1.3.0)\n",
      "Requirement already satisfied: importlib-metadata>=4.4 in /opt/conda/lib/python3.7/site-packages (from markdown>=2.6.8->tensorboard>=2.2.0->pytorch-lightning) (4.8.2)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.7/site-packages (from requests->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning) (2021.10.8)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.7/site-packages (from requests->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning) (1.26.7)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning) (2.8)\n",
      "Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/conda/lib/python3.7/site-packages (from requests->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning) (2.0.4)\n",
      "Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /opt/conda/lib/python3.7/site-packages (from aiohttp->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning) (4.0.1)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in /opt/conda/lib/python3.7/site-packages (from aiohttp->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning) (1.2.0)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.7/site-packages (from aiohttp->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning) (19.3.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.7/site-packages (from aiohttp->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning) (5.2.0)\n",
      "Requirement already satisfied: asynctest==0.13.0 in /opt/conda/lib/python3.7/site-packages (from aiohttp->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning) (0.13.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.7/site-packages (from aiohttp->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning) (1.2.0)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in /opt/conda/lib/python3.7/site-packages (from aiohttp->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning) (1.7.2)\n",
      "Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.7/site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard>=2.2.0->pytorch-lightning) (3.6.0)\n",
      "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /opt/conda/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard>=2.2.0->pytorch-lightning) (0.4.8)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in /opt/conda/lib/python3.7/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.2.0->pytorch-lightning) (3.1.1)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "!pip install pytorch-forecasting && pip install pytorch-lightning"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "realTraffic - occupancy_t4013.csv: Not enough obs. (390)\n",
      "realTraffic - speed_t4013.csv: Not enough obs. (390)\n",
      "realTraffic - occupancy_6005.csv: Not enough obs. (388)\n",
      "realTraffic - speed_6005.csv: Not enough obs. (407)\n",
      "realTraffic - speed_7578.csv: Not enough obs. (220)\n",
      "realKnownCause - rogue_agent_key_hold.csv: Not enough obs. (445)\n",
      "realKnownCause - ec2_request_latency_system_failure.csv: Not enough obs. (337)\n",
      "realKnownCause - rogue_agent_key_updown.csv: Not enough obs. (445)\n",
      "realAWSCloudwatch - ec2_cpu_utilization_5f5533.csv: Not enough obs. (337)\n",
      "realAWSCloudwatch - ec2_cpu_utilization_825cc2.csv: Not enough obs. (337)\n",
      "realAWSCloudwatch - ec2_disk_write_bytes_c0d644.csv: Not enough obs. (337)\n",
      "realAWSCloudwatch - ec2_cpu_utilization_ac20cd.csv: Not enough obs. (337)\n",
      "realAWSCloudwatch - iio_us-east-1_i-a2eb1cd9_NetworkIn.csv: Not enough obs. (104)\n",
      "realAWSCloudwatch - ec2_network_in_257a54.csv: Not enough obs. (337)\n",
      "realAWSCloudwatch - ec2_cpu_utilization_53ea38.csv: Not enough obs. (337)\n",
      "realAWSCloudwatch - ec2_cpu_utilization_c6585a.csv: Not enough obs. (337)\n",
      "realAWSCloudwatch - elb_request_count_8c0756.csv: Not enough obs. (337)\n",
      "realAWSCloudwatch - ec2_cpu_utilization_fe7f93.csv: Not enough obs. (337)\n",
      "realAWSCloudwatch - ec2_disk_write_bytes_1ef3de.csv: Not enough obs. (395)\n",
      "realAWSCloudwatch - ec2_network_in_5abac7.csv: Not enough obs. (395)\n",
      "realAWSCloudwatch - rds_cpu_utilization_cc0c53.csv: Not enough obs. (337)\n",
      "realAWSCloudwatch - ec2_cpu_utilization_24ae8d.csv: Not enough obs. (337)\n",
      "realAWSCloudwatch - rds_cpu_utilization_e47b3b.csv: Not enough obs. (336)\n",
      "realAWSCloudwatch - ec2_cpu_utilization_77c1ca.csv: Not enough obs. (337)\n",
      "realAWSCloudwatch - grok_asg_anomaly.csv: Not enough obs. (386)\n",
      "2021-12-04,20:07:17.439 Global seed set to 42\n",
      "2021-12-04,20:07:18.172 GPU available: True, used: True\n",
      "2021-12-04,20:07:18.172 TPU available: False, using: 0 TPU cores\n",
      "2021-12-04,20:07:18.172 IPU available: False, using: 0 IPUs\n",
      "2021-12-04,20:07:20.815 Global seed set to 42\n",
      "2021-12-04,20:07:20.816 initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2\n",
      "realTraffic - occupancy_t4013.csv: Not enough obs. (390)\n",
      "realTraffic - speed_t4013.csv: Not enough obs. (390)\n",
      "realTraffic - occupancy_6005.csv: Not enough obs. (388)\n",
      "realTraffic - speed_6005.csv: Not enough obs. (407)\n",
      "realTraffic - speed_7578.csv: Not enough obs. (220)\n",
      "realKnownCause - rogue_agent_key_hold.csv: Not enough obs. (445)\n",
      "realKnownCause - ec2_request_latency_system_failure.csv: Not enough obs. (337)\n",
      "realKnownCause - rogue_agent_key_updown.csv: Not enough obs. (445)\n",
      "realAWSCloudwatch - ec2_cpu_utilization_5f5533.csv: Not enough obs. (337)\n",
      "realAWSCloudwatch - ec2_cpu_utilization_825cc2.csv: Not enough obs. (337)\n",
      "realAWSCloudwatch - ec2_disk_write_bytes_c0d644.csv: Not enough obs. (337)\n",
      "realAWSCloudwatch - ec2_cpu_utilization_ac20cd.csv: Not enough obs. (337)\n",
      "realAWSCloudwatch - iio_us-east-1_i-a2eb1cd9_NetworkIn.csv: Not enough obs. (104)\n",
      "realAWSCloudwatch - ec2_network_in_257a54.csv: Not enough obs. (337)\n",
      "realAWSCloudwatch - ec2_cpu_utilization_53ea38.csv: Not enough obs. (337)\n",
      "realAWSCloudwatch - ec2_cpu_utilization_c6585a.csv: Not enough obs. (337)\n",
      "realAWSCloudwatch - elb_request_count_8c0756.csv: Not enough obs. (337)\n",
      "realAWSCloudwatch - ec2_cpu_utilization_fe7f93.csv: Not enough obs. (337)\n",
      "realAWSCloudwatch - ec2_disk_write_bytes_1ef3de.csv: Not enough obs. (395)\n",
      "realAWSCloudwatch - ec2_network_in_5abac7.csv: Not enough obs. (395)\n",
      "realAWSCloudwatch - rds_cpu_utilization_cc0c53.csv: Not enough obs. (337)\n",
      "realAWSCloudwatch - ec2_cpu_utilization_24ae8d.csv: Not enough obs. (337)\n",
      "realAWSCloudwatch - rds_cpu_utilization_e47b3b.csv: Not enough obs. (336)\n",
      "realAWSCloudwatch - ec2_cpu_utilization_77c1ca.csv: Not enough obs. (337)\n",
      "realAWSCloudwatch - grok_asg_anomaly.csv: Not enough obs. (386)\n",
      "2021-12-04,20:08:06.184 Global seed set to 42\n",
      "2021-12-04,20:08:06.977 Global seed set to 42\n",
      "2021-12-04,20:08:06.978 initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2\n",
      "\n",
      "datascience-1-0-ml-g4dn-12xlarge-deccbc1ffd85298aa1d775198510:701:701 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]\n",
      "NCCL version 2.7.8+cuda11.0\n",
      "\n",
      "datascience-1-0-ml-g4dn-12xlarge-deccbc1ffd85298aa1d775198510:789:789 [1] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]\n",
      "2021-12-04,20:08:10.455 ----------------------------------------------------------------------------------------------------\n",
      "distributed_backend=nccl\n",
      "All distributed processes registered. Starting with 2 processes\n",
      "----------------------------------------------------------------------------------------------------\n",
      "\n",
      "2021-12-04,20:08:10.467 LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3]\n",
      "2021-12-04,20:08:10.467 LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]\n",
      "2021-12-04,20:08:10.701 \n",
      "   | Name                               | Type                            | Params\n",
      "----------------------------------------------------------------------------------------\n",
      "0  | loss                               | QuantileLoss                    | 0     \n",
      "1  | logging_metrics                    | ModuleList                      | 0     \n",
      "2  | input_embeddings                   | MultiEmbedding                  | 22.4 K\n",
      "3  | prescalers                         | ModuleDict                      | 200   \n",
      "4  | static_variable_selection          | VariableSelectionNetwork        | 300   \n",
      "5  | encoder_variable_selection         | VariableSelectionNetwork        | 35.2 K\n",
      "6  | decoder_variable_selection         | VariableSelectionNetwork        | 18.7 K\n",
      "7  | static_context_variable_selection  | GatedResidualNetwork            | 40.6 K\n",
      "8  | static_context_initial_hidden_lstm | GatedResidualNetwork            | 40.6 K\n",
      "9  | static_context_initial_cell_lstm   | GatedResidualNetwork            | 40.6 K\n",
      "10 | static_context_enrichment          | GatedResidualNetwork            | 40.6 K\n",
      "11 | lstm_encoder                       | LSTM                            | 323 K \n",
      "12 | lstm_decoder                       | LSTM                            | 323 K \n",
      "13 | post_lstm_gate_encoder             | GatedLinearUnit                 | 20.2 K\n",
      "14 | post_lstm_add_norm_encoder         | AddNorm                         | 200   \n",
      "15 | static_enrichment                  | GatedResidualNetwork            | 50.6 K\n",
      "16 | multihead_attn                     | InterpretableMultiHeadAttention | 25.2 K\n",
      "17 | post_attn_gate_norm                | GateAddNorm                     | 20.4 K\n",
      "18 | pos_wise_ff                        | GatedResidualNetwork            | 40.6 K\n",
      "19 | pre_output_gate_norm               | GateAddNorm                     | 20.4 K\n",
      "20 | output_layer                       | Linear                          | 707   \n",
      "----------------------------------------------------------------------------------------\n",
      "1.1 M     Trainable params\n",
      "0         Non-trainable params\n",
      "1.1 M     Total params\n",
      "4.255     Total estimated model params size (MB)\n",
      "2021-12-04,20:08:11.838 Global seed set to 42                                   \n",
      "2021-12-04,20:08:11.838 Global seed set to 42\n",
      "Epoch 0:  18%|▏| 56/315 [00:46<03:33,  1.21it/s, loss=233, v_num=2, train_loss_s^C\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/temporal-fusion-transformer/train_tft.py\", line 184, in <module>\n",
      "    torch.save(tft.state_dict(), MODEL_PATH)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 369, in save\n",
      "    with _open_file_like(f, 'wb') as opened_file:\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 230, in _open_file_like\n",
      "    return _open_file(name_or_buffer, mode)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 211, in __init__\n",
      "    super(_open_file, self).__init__(open(name, mode))\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Colab_Notebooks/model/tft.pt'\n",
      "\u001b[0mTraceback (most recent call last):\n",
      "  File \"train_tft.py\", line 184, in <module>\n",
      "    torch.save(tft.state_dict(), MODEL_PATH)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 369, in save\n",
      "    with _open_file_like(f, 'wb') as opened_file:\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 230, in _open_file_like\n",
      "    return _open_file(name_or_buffer, mode)\n",
      "  File \"/opt/conda/lib/python3.7/site-packages/torch/serialization.py\", line 211, in __init__\n",
      "    super(_open_file, self).__init__(open(name, mode))\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Colab_Notebooks/model/tft.pt'\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "!cd time-series-forecasting && PL_TORCH_DISTRIBUTED_BACKEND=gloo && export NCCL_P2P_DISABLE=1 && export NCCL_IB_DISABLE=1 && export NCCL_DEBUG=WARN && python train_tft.py --local"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "instance_type": "ml.g4dn.12xlarge",
  "kernelspec": {
   "display_name": "Python 3 (Data Science)",
   "language": "python",
   "name": "python3__SAGEMAKER_INTERNAL__arn:aws:sagemaker:us-east-1:081325390199:image/datascience-1.0"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
